/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import chartbrew from "@chartbrew/plugin-strapi/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import documentation from "@strapi/plugin-documentation/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    chartbrew: chartbrew,
    "strapi-cloud": strapiCloud,
    documentation: documentation,
    "users-permissions": usersPermissions,
  },
});
